name: Release
on:
  push:
    tags:
      - '1*'

jobs:
  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install dependencies
        run: npm install
      - name: package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/build/OtterSGPrintProxy Setup 4.6.0.exe # Adjust the path
          asset_name: OtterSGPrintProxy Setup 4.6.0.exe.zip
          asset_content_type: application/zip # Adjust content type if needed

